version: "3"

services:
  keycloak:
    container_name: keycloak 
    command: start-dev
    image: quay.io/keycloak/keycloak:latest
    restart: "no"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
    - ./config/declarative:/kong/declarative/:rwx  
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"