version: "3"

networks:
 kong-net:
  driver: bridge
  name: kong-net

services:
  kong:
    container_name: kong-dbless 
    image: kong/kong-gateway:3.1.1.3
    restart: "no"
    networks:
      - kong-net
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_LICENSE_DATA:  
    volumes:
    - ./config/declarative:/kong/declarative/:rwx  
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    extra_hosts:
      - "host.docker.internal:host-gateway"